### ISSUE TITLE
Good Work

### ISSUE THREAD

**Issue by TormentedSoul666** [enty8080/Mr-Orbot#1]
Nice work!
Are you aware of [RouterSploit](https://github.com/threat9/routersploit)? 
It might be interesting for you, because it has also a modulary approach concerning exploits and is also written in Python.

**Comment by enty8080** [comment]
Hello, @TormentedSoul666

Thanks, but I do not need RouterSploit. I have my own modular exploitation framework that works better than RouterSploit.

My framework named HatSploit and developed in Python too.

HatSploit has improved handler, sessions, exploits, payloads and Windows, macOS, Unix, Android, iPhoneOS, Cisco IOS attack vectors. Also GUI comes soon with nice and comfortable interface.

You can find it here:
https://hatsploit.netlify.app/

I think it’s better than RouterSploit because RouterSploit’s attack methods and payload senders are deprecated. Also HatSploit supports a lot of platforms to attack, when RouterSploit attacks only routers and cameras.

**P.S.** HatSploit is on development stage, so bugs are expected and issues are opened for reporting them.

Regards,
Ivan Nikolsky (@enty8080)
